### PR TITLE
Branch bugs

### LINKED ISSUE #231: [PE-D][Tester C] Export format in implementation does not match stated Non-Functional Requirements in Developer Guide
**Description:** The Non-Functional Requirements state that the application should support exporting data in CSV or JSON format. However, the implemented export feature only supports exporting data to an HTML file.

**Expected Result:** Export functionality should align with the documented requirement (support CSV/JSON), or the documentation should accurately reflect the implemented behavior.

**Actual Result:** Only HTML export is supported, contradicting the stated requirement.

**Justification**: This inconsistency between documentation and implementation may mislead developers and users about the system’s capabilities.

Image

NFR portability requirements as documented in Developer Guide 

Image

Actual export behaviour as documented in User Guide

-------------
Labels: `severity.Medium` `type.DocumentationBug`

### LINKED ISSUE #245: [PE-D][Tester B] Command delete 0 produces a generic invalid command error instead of an invalid index error
Description:
Running delete 0 after a find command (or on the full list) produces a generic "invalid command format" error instead of a meaningful invalid index message. The UG specifies that the index must be a positive integer, so delete 0 should produce a clear index-related error.

Steps to reproduce:

1) Run find n/Bowie
2) Run delete 0
3) Observe the error message

Expected: 
A clear error message indicating the index is invalid, such as "Index is not a non-zero unsigned integer" or "The input number is out of range."

Image

Actual: 
A generic "invalid command" error is shown, which gives the user no clear indication of what went wrong.

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #246: [PE-D][Tester B] Command attach 0 produces generic invalid command error instead of a specific invalid index error
Description:
When the user runs attach 0 with any image path, the app displays a generic invalid command format error instead of a specific invalid index error. The index 0 is not a valid positive integer and should be clearly rejected with an index-related error message, consistent with how other index-based commands handle out-of-range or invalid index inputs.

Steps to reproduce:

1) Run attach 0 images/Bowie.jpg
2) Observe the error message

Expected (attach 9 images/Bowie.jpg),
Image

Actual (attach 0 images/Bowie.jpg),
Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #272: [PE-D][Tester A] Able to attach .html file as image
Steps to reproduce
1. Add a cat info
2. Attach the image with command: attach 2 images/issue.html

It successfully ran the command without invalid command of saying only image type file is supported.

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #279: [PE-D][Tester C] Inconsistent error messages for invalid index inputs in delete command
**Description:** The delete command handles invalid indices inconsistently depending on the input value. Inputs such as delete 10 and delete -1 are both invalid index cases, but produce different error messages.

**Steps to Reproduce:**
1. Run delete 10 
2. Observe “The cat index provided is invalid”
3. Run delete -1
4. Observe:
“Invalid command format! 
delete: Deletes the cat identified by the index number or name (case-sensitive) in the displayed cat list.
Parameters: INDEX (must be a positive integer) or CAT_NAME
Example: delete 1
Example: delete Whiskers"
 
**Expected Result:** All invalid index inputs should produce a consistent error message indicating invalid index usage.

**Actual Result:** Different error messages are shown depending on whether the index is negative or out-of-range.

**Justification:** The system does not consistently classify invalid index inputs, leading to inconsistent user feedback and potential confusion.

Image
Generic error message for "delete -1"

Image
Specific error message for "delete 10", where there are less than 10 cats on the list.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #281: [PE-D][Tester D] Attach missing file behavior in UG contradicts behavior
UG states that if the image file is missing, the card will simply show no photo and data remains unaffected. In code, attach fails fast with an error when the file does not exist, and will show the previous photo if it already had an image attached previously.

Steps to reproduce:
1. Run `attach 1 images/test.png`
2. Observe command failure with file-not-found message, and image stays the same as the previous image, instead of showing no image.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #282: [PE-D][Tester D] Glossary in DG uses incorrect term Contacts for Model
Glossary defines Model as holding contacts and user preferences.
Glossary should consistently use cat-record domain terminology to avoid reader confusion.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #283: [PE-D][Tester E] attach accepts non-image files even though CatPals documents only image formats
CatPals accepts non-image files in the `attach` command even though the documentation says cat photos should use supported image formats such as `.png`, `.jpg`, and `.jpeg`.

Steps to reproduce:
1. Launch the app.
2. Run `attach Bowie CatPals_User_Guide.pdf`.

Expected:
The command should reject the file because it is not an image.

Actual:
The command succeeds and stores the PDF path as the cat's image path.

Why this is problematic:
Users are told that CatPals works with image files, and the DG also says unsupported file types should be rejected. Accepting arbitrary existing files makes the feature behave differently from what the documentation promises.

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #284: [PE-D][Tester E] export saves HTML to the launch directory instead of beside catpals.jar
The User Guide says exported files are saved in the same folder as `catpals.jar`, but the actual output location depends on the current working directory used to launch the app.

Steps to reproduce:
1. Launch the app with `java -jar catpals.jar` in a different directory other than the one that the jar file is in.
2. Run `export`.
3. Check where `export.html` is created.

Expected:
`export.html` should be saved in the same folder as `catpals.jar`.

Actual:
`export.html` is created in the current working directory used to launch the app instead.

Why this is problematic:
Users following the UG may look for exported files in the wrong place. This is especially confusing because the app already depends on the launch directory for relative paths, so file-location behavior should be documented precisely.

Image

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by LexiAKAtiff**

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/UpdateCommandParser.java [hunk 1]
```diff
@@ -64,7 +65,7 @@ public UpdateCommand parse(String args) throws ParseException {
             } catch (ParseException pe) {
                 if (preamble.matches("-?\\d+")) {
                     throw new ParseException(
-                            String.format(MESSAGE_INVALID_COMMAND_FORMAT, UpdateCommand.MESSAGE_USAGE), pe);
+                            String.format(MESSAGE_INVALID_CAT_DISPLAYED_INDEX, UpdateCommand.MESSAGE_USAGE), pe);
```
Comment (lang-jiaqi) [inline src/main/java/seedu/address/logic/parser/UpdateCommandParser.java:68]: thanks for the correction!

**Comment by lang-jiaqi** [comment]
LGTM !
